[package]
name = "iterative-solvers"
authors = ["Xiangong Tang <tangxiangong@gmail.com>"]
edition = "2024"
version = "0.2.1"
license = "MIT OR Apache-2.0"
description = "Iterative algorithms for solving linear systems"
repository = "https://github.com/tangxiangong/iterative-solvers"
readme = "README.md"
categories = ["mathematics"]
keywords = ["numerical-algorithm", "math", "cg"]
exclude = ["julia-bench", "py-iterative-solvers"]

[features]
default = ["nalgebra"]
nalgebra = ["dep:nalgebra", "dep:nalgebra-sparse"]
faer = ["dep:faer"]
ndarray = [
    "dep:ndarray",
    "dep:sprs",
    "dep:ndarray-linalg",
    "dep:blas-src",
    "dep:openblas-src",
]


[dependencies]
thiserror = "2"
# nalgebra backend, default
nalgebra = { version = "0.33", optional = true }
nalgebra-sparse = { version = "0.10", optional = true }
# faer backend
faer = { version = "0.22", optional = true }
ndarray-linalg = { version = "0.17", optional = true }
# ndarray backend
ndarray = { version = "0.16", features = [
    "matrixmultiply-threading",
], optional = true }
blas-src = { version = "0.11", features = ["openblas"], optional = true }
openblas-src = { version = "0.10", features = [
    "cblas",
    "system",
], optional = true }
sprs = { version = "0.11", optional = true }

# docs.rs 配置
[package.metadata.docs.rs]
features = ["nalgebra"]
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "iterative_solvers"
doctest = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[dev-dependencies]
criterion = "0.6.0"
nalgebra = "0.33"
nalgebra-sparse = "0.10"
faer = "0.22"
ndarray = "0.16"
sprs = "0.11"

[[bench]]
name = "diagm"
harness = false

[[bench]]
name = "cg"
harness = false
