[project]
name = "iterative-solvers"
version = "0.1.0"
description = "Iterative algorithms for solving linear systems"
readme = "README.md"
license = { text = "MIT OR Apache-2.0" }
authors = [{ name = "Xiangong Tang", email = "tangxiangong@gmail.com" }]
requires-python = ">=3.9"
dependencies = ["numpy>=2.0.2", "scipy>=1.13.1"]

[tool.maturin]
module-name = "iterative_solvers._core"
python-packages = ["iterative_solvers"]
python-source = "python"
features = ["pyo3/extension-module"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
