name: Rust

on:
  push:
    branches: [ "dev", "stable" ]
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'rust-toolchain.toml'
      - '.cargo/**'
      - '!**/*.md'
      - '!docs/**'
      - '!py-iterative-solvers/**'
  pull_request:
    branches: [ "dev", "stable" ]
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'rust-toolchain.toml'
      - '.cargo/**'
      - '!**/*.md'
      - '!docs/**'
      - '!py-iterative-solvers/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y pkg-config libfreetype6-dev libfontconfig1-dev
    - name: Build nalgebra
      run: cargo build --verbose --no-default-features --features nalgebra
    - name: Build faer
      run: cargo build --verbose --no-default-features --features faer
    - name: Run tests nalgebra
      run: cargo test --verbose --no-default-features --features nalgebra
    - name: Run tests faer
      run: cargo test --verbose --no-default-features --features faer
